version: "3.9"
services:
  app1:
    build: app1/.
    expose:
      - "8080"
    ports:
      - "8081:8080"
    depends_on:
      - app2
    networks:
      backend:
  
  app2:
    build: app2/.
    image: app2
    #not exposing any ports as this service is no need to be visible outside the backend network 
    # expose:
    #   - "8088"
    # ports:
    #   - "8082:8088"
    networks:
      backend:
networks:
      backend:
   

 
